# Generated by Django 5.0.7 on 2024-07-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isko', '0002_alter_applicant_gwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
