# Generated by Django 5.0.7 on 2024-07-12 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isko', '0003_remove_user_first_name_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gwa',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(99.99), django.core.validators.MinValueValidator(90.0)]),
        ),
    ]
